# Generated by Django 5.0.4 on 2024-04-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_products_listing_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_listing',
            name='old_price',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
