# Generated by Django 5.0.4 on 2024-04-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_products_listing_photo_1_products_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_listing',
            name='product_description',
            field=models.TextField(null=True),
        ),
    ]
