# Generated by Django 5.0.4 on 2024-04-30 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('blog_img', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
