# Generated by Django 5.0.4 on 2024-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='details',
        ),
        migrations.AddField(
            model_name='blogs',
            name='long_details',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='blogs',
            name='short_details',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
