# Generated by Django 5.0.4 on 2024-04-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogs_details_blogs_long_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='long_details',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='short_details',
        ),
    ]
