# Generated by Django 5.0.4 on 2024-05-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogs_img1_blogs_img2_blogs_img3_blogs_img4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='img4',
        ),
    ]
