# Generated by Django 5.0.4 on 2024-05-04 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_messege_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_comment',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
